apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-job-latest
  namespace: phoenix
spec:
  template:
    spec:
      containers:
        - name: migrate-latest
          image: registry1234.mooo.com/admin/kubernetes_phoenix:latest # use your own registry
          command:
            [
              "bin/kubernetes_phoenix",
              "eval",
              "KubernetesPhoenix.Release.migrate",
            ]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: phoenix-secrets
                  key: postgres_url
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: phoenix-secrets
                  key: secret_key_base
      imagePullSecrets:
        - name: regcred
      restartPolicy: Never
